[package]
name = "kernel"
version = "0.1.0"
authors = ["ikh"]
edition = "2021"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[lib]
crate-type = [ "staticlib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.73"

[dependencies]
spin = "0.9.2"
volatile = "0.4.4"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
