[package]
name = "kernel"
version = "0.1.0"
authors = ["ikh"]
edition = "2018"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[lib]
crate-type = [ "staticlib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "^1.0.52"

[dependencies]
volatile = "^0.2.6"
